Biallelic filtering and bcftools comparison
David-Peede/mentee_research pull request #5
Opened 2022-04-05 05:44 UTC by briankirz

biallelic.py filters out all non-biallelic snps from a gzipped vcf file and writes them to a new vcf file.

compare_vcf confirms its accuracy with another output file resulting from a bcftools call to do the same.

2022-04-06 15:39 UTC, David-Peede requested changes
- [x]  Add the `bcftools` command in a shell script and annotate
- [ ]  Annotate every line of your python functions
- [x] Incorporate the `INFO` field's `VT` flag
- [ ] Add a README.MD File briefly explaining (one sentence) what each script in this directory does

2022-04-13 19:10 UTC, David-Peede requested changes
- [x] make the README.MD formatted as a markdown file
- [ ] write the bcf_biallelic.sh as shell file that you will submit to oscar (if you get stuck look at my example [here](https://github.com/David-Peede/BIOL1435/blob/main/OSCAR/get1KsampleFile.sh) or at the [documentation](https://docs.ccv.brown.edu/oscar/submitting-jobs/shared-machine))
- [ x] look at my `tgp_site_info` function starting on line 200 from [here](https://github.com/David-Peede/targt_pipeline_vcf/blob/master/vcf_functions.py) and update your `biallelic.py` function for readability purposes (also once you open a file you don't need to open it again)
- [ ] run all of this on chromosome 20 and if everything looks good then run on chromosme 1 (currently I believe bcftools and your parser will not produce identical VCFs) 
- [ ] create a `run_me.sh` which shows how to run all of the code on oscar

2022-04-14 18:56 UTC, briankirz commented
Question about SLURM jobs:
What I got from our meeting yesterday was that I was doing computational work locally, while I should have been shell files/SLURM scripts in order to submit the job to OSCAR.
My understanding is that this is done by including #SBATCH parameters in the header. However, in your get1KsampleFile.sh example, I'm not noticing any header parameters for input.
If I want to execute the same code on two different files (ie, chromosome 1 and chromosome 20), how would I indicate their different input files? Would I have to change the job manually each time I do it? I searched "input" in the full SLURM documentation but all I found was something related to `sattach` and I feel like I'm going down the wrong road again
<img width="728" alt="Screen Shot 2022-04-14 at 2 56 10 PM" src="https://user-images.githubusercontent.com/38798045/163457986-cbfa80c0-4423-466f-86db-568f2cba4400.png">
.

2022-04-14 19:16 UTC, briankirz commented
I'm wondering about how to run input into the SLURM job.
I want to load bcftools and then execute the command on a specific file. Here's what I've got so far
<img width="841" alt="Screen Shot 2022-04-14 at 3 15 42 PM" src="https://user-images.githubusercontent.com/38798045/163460647-ab129c1e-d302-473b-bce5-ea3296a443f4.png">
I found --input=<name> in the SLURM documentation but I'm not sure how to use the name of that file. Will I need to hardcode a different SLURM job for the same command being run on different files?

2022-04-14 19:23 UTC, briankirz commented
"also once you open a file you don't need to open it again" as it relates to biallelic.py
Not sure what you mean by this

2022-04-14 19:56 UTC, David-Peede commented
> 

Look back through my tutorial on OSCAR. The SLURM header is just to request resources NOT EXECUTE CODE. You are still writing in python but bcftools is a command line tool much like doing `cd` or `pwd`

2022-04-14 19:57 UTC, David-Peede commented
> "also once you open a file you don't need to open it again" as it relates to biallelic.py Not sure what you mean by this

`with gzip.open(vcf_input, 'rb') as gz, open(vcf_output, 'w') as f:` you only need the first open

2022-04-14 20:18 UTC, briankirz commented
When I compare vcfs in compare_vcf.py, should I be preparing for the headers of each file to not necessarily be the same length? This is taking longer to implement, as I see that the file created by a SLURM job has a different header than the one created by my python code.

It would be much easier to implement if both files were identical (including headers), but I'm not sure that there's a way to do this where I can assume that.

2022-04-14 21:05 UTC, David-Peede commented
> When I compare vcfs in compare_vcf.py, should I be preparing for the headers of each file to not necessarily be the same length? This is taking longer to implement, as I see that the file created by a SLURM job has a different header than the one created by my python code.
> 
> It would be much easier to implement if both files were identical (including headers), but I'm not sure that there's a way to do this where I can assume that.

Just skip any line starting with a `##` or `#` and there shouldn't be any problems

2022-04-15 22:37 UTC, briankirz commented
Two things:
1) including the -I (exclude indels) argument in the second command results in an output that is blank besides the SLURM header
<img width="769" alt="Screen Shot 2022-04-15 at 6 28 10 PM" src="https://user-images.githubusercontent.com/38798045/163649405-3dd59efc-3923-4db4-81f3-d2b3043440a1.png">

However, without the -I it works fine. I'll keep experimenting

2022-07-01 16:15 UTC, David-Peede requested changes
clean up file names and code

2022-07-01 16:15 UTC, David-Peede commented on kirz/vcf_processing/README.MD
> +# Filtering chromosomes to include only biallelic SNPS
- [x]  brief description of the purpose of this repo
- [x]  brief description of the code scripts including input and output description 
- [x] brief description of the other directories and what they contain
- [x] step by step example of how to recreate the analyses

2022-07-12 21:58 UTC, David-Peede requested changes
- [ ] fix readme
- [ ] remove unnecessary files

2022-07-12 21:58 UTC, David-Peede commented on kirz/vcf_processing/README.MD
> +# Filtering chromosomes to include only biallelic SNPS
- [ ] fix bash one liners

2022-07-12 21:58 UTC, David-Peede commented on kirz/vcf_processing/bcf_biallelic.sh
> +#!/bin/bash
- [ ] remove this file

2022-07-18 21:21 UTC, David-Peede approved these changes

2022-07-18 21:21 UTC, merged